# Generated by Django 5.2.15 on 2026-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salinity',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tds',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='watertable',
            name='date',
            field=models.DateField(),
        ),
    ]
