# Generated by Django 5.2.15 on 2026-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0002_alter_salinity_date_alter_tds_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GISLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('original_file', models.CharField(max_length=255)),
                ('geometry_type', models.CharField(blank=True, max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
