# Generated by Django 5.2.15 on 2026-07-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('Rr', models.FloatField(default=0)),
                ('Re', models.FloatField(default=0)),
                ('Ri', models.FloatField(default=0)),
                ('I', models.FloatField(default=0)),
                ('Si', models.FloatField(default=0)),
                ('Se', models.FloatField(default=0)),
                ('O', models.FloatField(default=0)),
                ('Et', models.FloatField(default=0)),
                ('Dp', models.FloatField(default=0)),
                ('delta_s', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
