# Generated by Django 5.2.15 on 2026-07-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0006_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('district', models.CharField(blank=True, default='', max_length=150)),
                ('state', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='waterbalance',
            name='village_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_balances', to='groundwater.villagecluster'),
        ),
    ]
