# Generated by Django 5.2.15 on 2026-07-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0007_villagecluster_waterbalance_village_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbalance',
            name='village_cluster',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('Village', 'Village'), ('Town', 'Town'), ('City', 'City'), ('Taluka', 'Taluka'), ('District', 'District'), ('Watershed', 'Watershed'), ('River Basin', 'River Basin')], default='Village', max_length=30)),
                ('district', models.CharField(blank=True, default='', max_length=150)),
                ('state', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='groundwater.location')),
            ],
        ),
        migrations.AddField(
            model_name='waterbalance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_balances', to='groundwater.location'),
        ),
        migrations.DeleteModel(
            name='VillageCluster',
        ),
    ]
