# Generated by Django 5.2.15 on 2026-07-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0008_remove_waterbalance_village_cluster_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbalance',
            name='date',
        ),
    ]
