# Generated by Django 5.2.15 on 2026-07-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0009_remove_waterbalance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumping',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pumping_records', to='groundwater.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salinity',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salinity_records', to='groundwater.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tds',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tds_records', to='groundwater.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_levels', to='groundwater.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watertable',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_tables', to='groundwater.location'),
            preserve_default=False,
        ),
    ]
